#!/usr/bin/env node
const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');

const menu = require('./src/Model/Menu');
const Args = require('./src/Model/Args');

const A11yController = require('./src/Controller/A11yController');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    console.log('\nStarting A11y Tests');
    let a11yController = new A11yController(args);
    a11yController.start().then();
}